"""Fixture builder for poisoned-fixture modules.

Reads a payload from stdin, validates it against a rule's regex (or, in
``--negative`` mode, confirms it does *not* match), and writes a Python module
that exports the payload as base64 plus integrity constants. The module the
tool writes is the only file in the round trip that gets stored in the repo;
the raw payload itself never leaves the user's machine and is never echoed
back to the terminal.

Phase 1 exercises the positive, ASCII-only path. ``--negative`` and
``--allow-unicode`` are wired but not stress-tested until Phase 2.
"""

from __future__ import annotations

import base64
import hashlib
import importlib.util
import sys
import textwrap
from pathlib import Path
from typing import IO

import click
import regex as re

from agentguard.config import Config, Rule, load_config


def run(
    rule_id: str,
    out_path: Path,
    *,
    negative: bool = False,
    allow_unicode: bool = False,
    payload_source: IO[str] | None = None,
    cfg: Config | None = None,
) -> None:
    """Read payload from ``payload_source``, encode + verify, emit module at ``out_path``."""
    cfg = cfg if cfg is not None else load_config()
    rule = cfg.rule_by_id(rule_id)

    source = payload_source if payload_source is not None else sys.stdin
    payload = source.read().rstrip("\r\n")
    _validate_payload(payload, allow_unicode=allow_unicode)

    match = re.search(rule.pattern, payload)
    if not negative and match is None:
        raise click.ClickException(
            f"Rule {rule_id} regex did not match payload."
        )
    if negative and match is not None:
        raise click.ClickException(
            f"--negative requires no match, but rule {rule_id} did match payload."
        )

    constants = _compute_constants(payload, match, rule)
    _emit_module(out_path, rule, constants, negative=negative)
    _verify_emitted(out_path, constants)
    click.echo(_summary_line(out_path, rule, constants))


def _validate_payload(payload: str, *, allow_unicode: bool) -> None:
    if not payload:
        raise click.ClickException("Payload is empty.")
    if not allow_unicode:
        if not payload.isascii():
            raise click.ClickException(
                "Payload contains non-ASCII characters. Pass --allow-unicode for UNI* rules."
            )
        for ch in payload:
            if ch in ("\t", "\n"):
                continue
            if not 0x20 <= ord(ch) <= 0x7E:
                raise click.ClickException(
                    "Payload contains a non-printable ASCII control character. "
                    "Only tab, newline, and printable ASCII (0x20-0x7E) are allowed."
                )


def _compute_constants(
    payload: str, match: re.Match[str] | None, rule: Rule
) -> dict[str, object]:
    payload_bytes = payload.encode("utf-8")
    payload_b64 = base64.b64encode(payload_bytes).decode("ascii")
    payload_sha = hashlib.sha256(payload_bytes).hexdigest()

    if match is not None:
        match_text = match.group(0)
        match_bytes = match_text.encode("utf-8")
        match_sha = hashlib.sha256(match_bytes).hexdigest()
        match_len: int | None = len(match_bytes)
    else:
        match_sha = None
        match_len = None

    category_severity = dict(sorted(rule.category_severity.items()))
    assert all(
        isinstance(k, str) and isinstance(v, str)
        for k, v in category_severity.items()
    ), "category_severity keys and values must be str"

    return {
        "payload_b64": payload_b64,
        "payload_sha": payload_sha,
        "payload_len": len(payload_bytes),
        "match_sha": match_sha,
        "match_len": match_len,
        "rule_id": rule.id,
        "category_severity": category_severity,
    }


def _emit_module(
    out_path: Path,
    rule: Rule,
    constants: dict[str, object],
    *,
    negative: bool,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)

    match_sha_repr = (
        repr(constants["match_sha"]) if constants["match_sha"] is not None else "None"
    )
    match_len_repr = (
        repr(constants["match_len"]) if constants["match_len"] is not None else "None"
    )

    header = textwrap.dedent(
        f'''\
        """Generated by ``agentguard fixture-make`` for rule {rule.id}. Do not edit by hand.

        Payload is stored as base64 to keep the literal injection prose out of any
        reader's context (IDEs, stack traces, git diffs). Decode only via
        ``tests.fixtures._helpers.materialize`` (automation) or ``inspect`` (manual
        human review). See repo CLAUDE.md for the full protocol.
        """

        '''
    )

    body = textwrap.dedent(
        f"""\
        PAYLOAD_B64 = {constants["payload_b64"]!r}

        EXPECTED_PAYLOAD_SHA256 = {constants["payload_sha"]!r}
        EXPECTED_PAYLOAD_LEN = {constants["payload_len"]!r}

        EXPECTED_MATCH_SHA256 = {match_sha_repr}
        EXPECTED_MATCH_LEN = {match_len_repr}

        EXPECTED = {{
            "rule_id": {rule.id!r},
            "negative": {negative!r},
            "category_severity": {constants["category_severity"]!r},
        }}
        """
    )

    out_path.write_text(header + body, encoding="utf-8", newline="\n")


def _verify_emitted(out_path: Path, constants: dict[str, object]) -> None:
    """Re-decode emitted PAYLOAD_B64 and re-hash to confirm round-trip integrity."""
    spec = importlib.util.spec_from_file_location(
        "_agentguard_emitted_verify", out_path
    )
    if spec is None or spec.loader is None:
        out_path.unlink(missing_ok=True)
        raise click.ClickException(
            "Self-verification failed: could not load emitted module spec."
        )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    decoded = base64.b64decode(module.PAYLOAD_B64)
    actual_sha = hashlib.sha256(decoded).hexdigest()
    if actual_sha != constants["payload_sha"]:
        out_path.unlink(missing_ok=True)
        raise click.ClickException(
            "Self-verification failed: emitted PAYLOAD_B64 hash does not match "
            "the hash computed before write. Output deleted."
        )


def _summary_line(
    out_path: Path, rule: Rule, constants: dict[str, object]
) -> str:
    match_sha = constants["match_sha"]
    match_len = constants["match_len"]
    if match_sha is not None:
        match_field = f"  match:   {match_len} bytes  sha256={match_sha}"
    else:
        match_field = "  match:   (none — negative fixture)"
    return (
        f"Wrote {out_path}\n"
        f"  rule:    {rule.id}\n"
        f"  payload: {constants['payload_len']} bytes  sha256={constants['payload_sha']}\n"
        f"{match_field}"
    )
